### ISSUE TITLE
Subscribe options are missing in arguments

### ISSUE THREAD

**Issue by justerest** [dmitry-korolev/push-js#1]
Привет!
Мне нравится твой модуль. Мне помог! Так как я вообще не разбирался с пуш. Но вот мне нужно applicationServerKey передать в subscribe, а этот метод у Тебя не принимает аргументов. Добавишь фичу, или мне самому дописать в своём проекте?

**Comment by dmitry-korolev** [comment]
@justerest привет. 
В общем-то, задача этого модуля и состоит в том, чтобы помочь разобраться, как оно работает =)
Его дальнейшее развитие пока не планируется.
Если хочется что-то готовое из коробки, я бы мог порекомендовать https://github.com/Nickersoft/push.js

**Comment by justerest** [comment]
Спасибо! Я этот модуль смотрел. Но как раз не понял, где там subscribed..) тогда на основе твоего кода все допишу)
